### ISSUE TITLE
Detect https://software.reuse new copyright syntax

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1816]
### Description
See https://github.com/fsfe/reuse-tool/blob/4fe435ad269e26df38d4c6a5abc4747908dac8cc/src/reuse/_comment.py#L2 in the form of:
```
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.
# SPDX-FileCopyrightText: 2019 Kirill Elagin
```

**Comment by hahasuperking** [comment]
@pombredanne  Can you please assign the ticket to me?

**Comment by carmenbianca** [comment]
SPDX recently formalised this in https://github.com/spdx/spdx-spec/pull/196

Though it's not formally released at the moment.

**Comment by pombredanne** [comment]
@carmenbianca :+1:  thanks!

**Comment by carmenbianca** [comment]
Might this be a duplicate of #1022? Or vice versa.

**Comment by rainerth** [comment]
Any plans to enhance scancode towards reuse / SPDX-2.1 compatibility? We use reuse for a new OS project and it would be fantastic to use scancode. Currently this kind of headers are not detected: 

// SPDX-FileCopyrightText: 2009-2020 Company, authors: Joe Doe
//
// SPDX-License-Identifier: MPL-2.0

Or 
// SPDX-FileCopyrightText: Company
// SPDX-FileContributor: authors: Joe Doe
// SPDX-FileContributor: modified by Bill Smith <bill@smi.th>
//
// SPDX-License-Identifier: MPL-2.0

**Comment by pombredanne** [comment]
These are detected alright:
```
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.
# SPDX-FileCopyrightText: 2019 Kirill Elagin
```
yield this with:
scancode -c --yaml -
```
        copyrights:
            -   copyright: Copyright 2019 Free Software Foundation Europe e.V.
                start_line: 1
                end_line: 1
            -   copyright: Copyright 2019 Kirill Elagin
                start_line: 2
                end_line: 2
        holders:
            -   holder: Free Software Foundation Europe e.V.
                start_line: 1
                end_line: 1
            -   holder: Kirill Elagin
                start_line: 2
                end_line: 2
```

**Comment by pombredanne** [comment]
> Any plans to enhance scancode towards reuse / SPDX-2.1 compatibility? We use reuse for a new OS project and it would be fantastic to use scancode. Currently this kind of headers are not detected:
> 
> // SPDX-FileCopyrightText: 2009-2020 Company, authors: Joe Doe 
> // 
> // SPDX-License-Identifier: MPL-2.0
> 
> Or 
> // SPDX-FileCopyrightText: Company 
> // SPDX-FileContributor: authors: Joe Doe 
> // SPDX-FileContributor: modified by Bill Smith [bill@smi.th](mailto:bill@smi.th) 
> // 
> // SPDX-License-Identifier: MPL-2.0

@rainerth   The SPDX-FileContributor is SPDX alright but seldom seen used in a file and not a reuse spec...It would be easy enough to add this as an "author" tag in ScanCode ... I can see enough instances of it in the wild to add it 

So I pushed this https://github.com/nexB/scancode-toolkit/pull/2838
and now we get this:
```
 * SPDX-FileCopyrightText: 2008 Red Hat Inc.
 * SPDX-FileContributor: Adam Jackson <ajax@redhat.com>
 * SPDX-FileContributor: Bill Nottingham <notting@redhat.com>
 * SPDX-FileContributor: Ray Strode <rstrode@redhat.com>
```
detected as:
```
copyrights:
    -   copyright: Copyright 2008 Red Hat Inc.
        start_line: 1
        end_line: 1
holders:
    -   holder: Red Hat Inc.
        start_line: 1
        end_line: 1
authors:
    -   author: Adam Jackson <ajax@redhat.com>
        start_line: 2
        end_line: 2
    -   author: Bill Nottingham <notting@redhat.com>
        start_line: 3
        end_line: 3
    -   author: Ray Strode <rstrode@redhat.com>
        start_line: 4
        end_line: 4
```
