### ISSUE TITLE
Email is not detected properly in Python setup.py

### ISSUE THREAD

**Issue by rpotter12** [nexB/scancode-toolkit#1943]
### Description

Hi,
***I have mentioned this in gitter chat also***
I was trying to use scancode. I ran scancode for https://raw.githubusercontent.com/python/mypy/master/setup.py 

Commands used for mypy:
1. `wget https://raw.githubusercontent.com/python/mypy/master/setup.py`
2. `scancode setup.py --package --license --copyright --json-pp abc.json`

Output link for mypy project: https://drive.google.com/file/d/1Gc8xIRdy9pDd88L9Pk3SEcvZpfsnPHnU/view?usp=sharing  
***In this email is shown null but the original file contains the email***

### System configuration

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? `ScanCode version 3.1.1`
* What installation method was used to install/run scancode? `pip`

---
If this is a bug, then I would like to solve this bug :)

**Comment by rpotter12** [comment]
@pombredanne This bug is already solved in previous PRs. Please update the project on pypi also :)

**Comment by pombredanne** [comment]
This is fixed in develop and we detect this in https://raw.githubusercontent.com/python/mypy/v0.770/setup.py
```
                parties:
                    -   type: person
                        role: author
                        name: Jukka Lehtosalo
                        email: jukka.lehtosalo@iki.fi
```
