### ISSUE TITLE
Incorrect copyrights and authors in nuget.exe

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2597]
See https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/nuget.exe?raw=true
See below.
Only `Copyright (c) .NET Foundation` seems correct
```
copyrights:
    -   copyright: Copyright (c) .NET Foundation
        start_line: 9317
        end_line: 9317
    -   copyright: Copyright TargetPath IncludeSymbols
        start_line: 47314
        end_line: 47316
    -   copyright: Copyright GetProperty EvaluatedValue
        start_line: 57164
        end_line: 57166
holders:
    -   holder: NET Foundation
        start_line: 9317
        end_line: 9317
    -   holder: TargetPath IncludeSymbols
        start_line: 47315
        end_line: 47316
    -   holder: GetProperty EvaluatedValue
        start_line: 57165
        end_line: 57166
authors:
    -   author: signed. Failed
        start_line: 10731
        end_line: 10732
    -   author: Repository. Unable
        start_line: 10771
        end_line: 10772
    -   author: Certificate Owners
        start_line: 25045
        end_line: 25047


```
