### ISSUE TITLE
Copyright scanner seems to include too much text

### ISSUE THREAD

**Issue by sutula** [nexB/scancode-toolkit#2700]
### Description

In the case below, the copyright scanner indicates that the copyright is three lines long.  From inspection, it seems that it is only one line.  I don't know exactly what terminates a copyright, but it seems like end-of-line should be significant.

### How To Reproduce

A scan of [list.rb](https://archive.softwareheritage.org/browse/content/sha1_git:f393dcaec40f83d5e7d9f4ac8a8a2a8c385bb334/raw/) yields the following:

"copyrights": [
        {
          "value": "Copyright (c) 2007-2010 Sharon Rosner, Wayne E. Seguin, Aman Gupta, Adrian Madrid, Jeremy Evans module List Set",
          "start_line": 51,
          "end_line": 53
        }
      ],

For ease of viewing, you can see the detected copyright in context [here](https://archive.softwareheritage.org/swh:1:cnt:f393dcaec40f83d5e7d9f4ac8a8a2a8c385bb334;lines=51-53).

scancode --json-pp ../scancode.json --copyright .

This was found on: Debian Linux, python 3.7.3, scancode-toolkit 21.8.4, installed from download of released Linux tar archive

**Comment by pombredanne** [comment]
@sutula Thanks for the report!
The solution is likely this patch in https://github.com/nexB/scancode-toolkit/blob/d8d272ab561b4448698eaf4c420c8775ba125d70/src/cluecode/copyrights.py#L944 to design Last and Set as plain nouns and not proper nouns:

```diff
diff --git a/src/cluecode/copyrights.py b/src/cluecode/copyrights.py
index 0caf90d..397790e 100644
--- a/src/cluecode/copyrights.py
+++ b/src/cluecode/copyrights.py
@@ -1044,6 +1044,8 @@
     (r'^JMagnetic$', 'NN'),
     (r'^Joint$', 'NN'),
     (r'^Jsunittest$', 'NN'),
+    (r'^List$', 'NN'),
+    (r'^Set$', 'NN'),
     (r'^Last$', 'NN'),
     (r'^LAW', 'NN'),
     (r'^Legal$', 'NN'),
```

and with this I get (with the YAML output for a change):
```YAML
$ scancode -c --yaml - a
Setup plugins...
Collect file inventory...
Scan files for: copyrights with 1 process(es)...
[####################] 2           
headers:
    -   tool_name: scancode-toolkit
        tool_version: 30.0.0
        options:
            input:
                - a
            --copyright: yes
            --yaml: '-'
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2021-09-14T202443.666527'
        end_timestamp: '2021-09-14T202443.777672'
        output_format_version: 1.0.0
        duration: '0.11117029190063477'
        message:
        errors: []
        extra_data:
            spdx_license_list_version: '3.14'
            files_count: 1
files:
    -   path: a
        type: file
        copyrights:
            -   value: Copyright (c) 2007-2010 Sharon Rosner, Wayne E. Seguin, Aman Gupta, Adrian
                    Madrid, Jeremy Evans
                start_line: 2
                end_line: 2
        holders:
            -   value: Sharon Rosner, Wayne E. Seguin, Aman Gupta, Adrian Madrid, Jeremy Evans
                start_line: 2
                end_line: 2
        authors: []
        scan_errors: []
```
