### ISSUE TITLE
False positive in copyright detection

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2714]
With:
```
for k in range(c):
    Ac = A[k*n_vis_ind:(k+1)*n_vis_ind, :].dot(alpha)
```

we should get nothing but have:
```
copyrights:
    -   value: (c) Ac A
        start_line: 1
        end_line: 2
```
