### ISSUE TITLE
Empty package-lock.json should not return packages

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2732]
An empty locfile should not return a package instance:
With this file named "package-lock.json":
```
{
  "lockfileVersion": 1
}
```
and this scancode command:
`scancode -p package-lock.json  --yaml -`

I get:
```
    -   path: package-lock.json
        type: file
        packages:
            -   type: npm
                namespace:
                name:
                version:
                qualifiers: {}
                subpath:
                primary_language: JavaScript
                description:
                release_date:
                parties: []
                keywords: []
                homepage_url:
                download_url:
                size:
                sha1:
                md5:
                sha256:
                sha512:
                bug_tracking_url:
                code_view_url:
                vcs_url:
                copyright:
                license_expression:
                declared_license:
                notice_text:
                root_path:
                dependencies: []
                contains_source_code:
                source_packages: []
                extra_data: {}
                purl:
                repository_homepage_url: https://www.npmjs.com/package/None
                repository_download_url: https://registry.npmjs.org/None/-/None-None.tgz
                api_data_url: https://registry.npmjs.org/None
        scan_errors: []
```
and I should not get any package reported and get this:
```
-   path: package-lock.json
    type: file
    packages: []

```
