### ISSUE TITLE
Incomplete proprietary license detected 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2764]
@tsteenbe reported to me that  https://raw.githubusercontent.com/SanjayBaby/device_x3/b218142b30a9f47b0aac3b971cd4c6bd2e4c6e9e/hal/m4u/2.0/Android.mk is not detected correctly.

The YAML scan output is:
```yaml
headers:
    -   tool_name: scancode-toolkit
        tool_version: 30.0.0
        options:
            input:
                - mt
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: '-'
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2021-11-20T082119.548928'
        end_timestamp: '2021-11-20T082122.081105'
        output_format_version: 2.0.0
        duration: '2.532198905944824'
        message:
        errors: []
        extra_data:
            spdx_license_list_version: '3.14'
            files_count: 1
files:
    -   path: mt
        type: file
        licenses:
            -   key: commercial-license
                score: '93.85'
                name: Commercial License
                short_name: Commercial License
                category: Commercial
                is_exception: no
                is_unknown: no
                owner: Unspecified
                homepage_url:
                text_url:
                reference_url: https://scancode-licensedb.aboutcode.org/commercial-license
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/commercial-license.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/commercial-license.yml
                spdx_license_key: LicenseRef-scancode-commercial-license
                spdx_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/commercial-license.LICENSE
                start_line: 1
                end_line: 8
                matched_rule:
                    identifier: commercial-license_proprietary_108.RULE
                    license_expression: commercial-license
                    licenses:
                        - commercial-license
                    referenced_filenames: []
                    is_license_text: no
                    is_license_notice: yes
                    is_license_reference: no
                    is_license_tag: no
                    is_license_intro: no
                    has_unknown: no
                    matcher: 3-seq
                    rule_length: 61
                    matched_length: 61
                    match_coverage: '100.0'
                    rule_relevance: 100
                matched_text: |
                    Copyright Statement:
                    #
                    # This software/firmware and related documentation ("[MediaTek] Software") are
                    # protected under relevant copyright laws. The information contained herein
                    # is confidential and proprietary to [MediaTek] Inc. and/or its licensors.
                    # Without the prior written permission of [MediaTek] inc. and/or its licensors,
                    # any reproduction, modification, use or disclosure of [MediaTek] Software,
                    # and information contained herein, in whole or in part, shall be strictly prohibited.
            -   key: public-domain-disclaimer
                score: '20.31'
                name: Public Domain Disclaimer
                short_name: Public Domain Disclaimer
                category: Public Domain
                is_exception: no
                is_unknown: no
                owner: Unspecified
                homepage_url:
                text_url:
                reference_url: https://scancode-licensedb.aboutcode.org/public-domain-disclaimer
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/public-domain-disclaimer.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/public-domain-disclaimer.yml
                spdx_license_key: LicenseRef-scancode-public-domain-disclaimer
                spdx_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/public-domain-disclaimer.LICENSE
                start_line: 15
                end_line: 17
                matched_rule:
                    identifier: public-domain-disclaimer_30.RULE
                    license_expression: public-domain-disclaimer
                    licenses:
                        - public-domain-disclaimer
                    referenced_filenames: []
                    is_license_text: yes
                    is_license_notice: no
                    is_license_reference: no
                    is_license_tag: no
                    is_license_intro: no
                    has_unknown: no
                    matcher: 3-seq
                    rule_length: 64
                    matched_length: 13
                    match_coverage: '20.31'
                    rule_relevance: 100
                matched_text: |
                    DISCLAIMS ANY [AND] [ALL] WARRANTIES,
                    # EXPRESS OR IMPLIED, [INCLUDING] [BUT] [NOT] [LIMITED] [TO] [THE] [IMPLIED] WARRANTIES OF
                    # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
            -   key: mit
                score: '45.95'
                name: MIT License
                short_name: MIT License
                category: Permissive
                is_exception: no
                is_unknown: no
                owner: MIT
                homepage_url: http://opensource.org/licenses/mit-license.php
                text_url: http://opensource.org/licenses/mit-license.php
                reference_url: https://scancode-licensedb.aboutcode.org/mit
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mit.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mit.yml
                spdx_license_key: MIT
                spdx_url: https://spdx.org/licenses/MIT
                start_line: 16
                end_line: 17
                matched_rule:
                    identifier: mit_758.RULE
                    license_expression: mit
                    licenses:
                        - mit
                    referenced_filenames: []
                    is_license_text: no
                    is_license_notice: yes
                    is_license_reference: no
                    is_license_tag: no
                    is_license_intro: no
                    has_unknown: no
                    matcher: 3-seq
                    rule_length: 37
                    matched_length: 17
                    match_coverage: '45.95'
                    rule_relevance: 100
                matched_text: |
                    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE [IMPLIED] WARRANTIES OF
                    # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE [OR] NONINFRINGEMENT.
        license_expressions:
            - commercial-license
            - public-domain-disclaimer
            - mit
        percentage_of_license_text: '16.2'
        scan_errors: []
```
