### ISSUE TITLE
two files with same license and copyright are classified differently (one erroneously)

### ISSUE THREAD

**Issue by kevbroch** [nexB/scancode-toolkit#2798]
### Description

two files with the exactly the same copyright and license header are classified different (and one erroneously).

```
==> toolchain.txt <==
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

==> yum-requirements.txt <==
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
```

csv results:

```
$ cat scancode-report.csv 
Resource,type,percentage_of_license_text,scan_errors,license_expression,license__key,license__score,license__name,license__short_name,license__category,license__is_exception,license__is_unknown,license__owner,license__homepage_url,license__text_url,license__reference_url,license__scancode_text_url,license__scancode_data_url,license__spdx_license_key,license__spdx_url,start_line,end_line,matched_rule__identifier,matched_rule__license_expression,matched_rule__licenses,matched_rule__referenced_filenames,matched_rule__is_license_text,matched_rule__is_license_notice,matched_rule__is_license_reference,matched_rule__is_license_tag,matched_rule__is_license_intro,matched_rule__has_unknown,matched_rule__matcher,matched_rule__rule_length,matched_rule__matched_length,matched_rule__match_coverage,matched_rule__rule_relevance,package__type,package__namespace,package__name,package__version,package__qualifiers,package__subpath,package__primary_language,package__description,package__release_date,package__homepage_url,package__download_url,package__size,package__sha1,package__md5,package__sha256,package__sha512,package__bug_tracking_url,package__code_view_url,package__vcs_url,package__copyright,package__license_expression,package__declared_license,package__notice_text,package__root_path,package__contains_source_code,package__extra_data,package__purl
toolchain.txt,file,10.37,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
toolchain.txt,,,,apache-2.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
toolchain.txt,,,,apache-2.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
toolchain.txt,,,,,apache-2.0,73.33,Apache License 2.0,Apache 2.0,Permissive,False,False,Apache Software Foundation,http://www.apache.org/licenses/,http://www.apache.org/licenses/LICENSE-2.0,https://scancode-licensedb.aboutcode.org/apache-2.0,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml,Apache-2.0,https://spdx.org/licenses/Apache-2.0,2,2,apache-2.0_464.RULE,apache-2.0,apache-2.0,LICENSE,,True,,,,,3-seq,15,11,73.33,100.00,,,,,,,,,,,,,,,,,,,,,,,,,,,
toolchain.txt,,,,,apache-2.0,100.00,Apache License 2.0,Apache 2.0,Permissive,False,False,Apache Software Foundation,http://www.apache.org/licenses/,http://www.apache.org/licenses/LICENSE-2.0,https://scancode-licensedb.aboutcode.org/apache-2.0,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml,Apache-2.0,https://spdx.org/licenses/Apache-2.0,3,3,spdx-license-identifier: apache-2.0,apache-2.0,apache-2.0,,,,,True,,,1-spdx-id,6,6,100.00,100.00,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,file,13.95,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,apache-2.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,unknown-license-reference,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,apache-2.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,,apache-2.0,100.00,Apache License 2.0,Apache 2.0,Permissive,False,False,Apache Software Foundation,http://www.apache.org/licenses/,http://www.apache.org/licenses/LICENSE-2.0,https://scancode-licensedb.aboutcode.org/apache-2.0,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml,Apache-2.0,https://spdx.org/licenses/Apache-2.0,2,2,apache-2.0_463.RULE,apache-2.0,apache-2.0,LICENSE,,True,,,,,2-aho,10,10,100.00,100.00,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,,unknown-license-reference,100.00,Unknown License file reference,Unknown License reference,Unstated License,False,True,Unspecified,,,https://scancode-licensedb.aboutcode.org/unknown-license-reference,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.yml,LicenseRef-scancode-unknown-license-reference,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE,2,2,unknown-license-reference_283.RULE,unknown-license-reference,unknown-license-reference,LICENSE,,,True,,,True,2-aho,4,4,100.00,100.00,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,,apache-2.0,100.00,Apache License 2.0,Apache 2.0,Permissive,False,False,Apache Software Foundation,http://www.apache.org/licenses/,http://www.apache.org/licenses/LICENSE-2.0,https://scancode-licensedb.aboutcode.org/apache-2.0,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE,https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml,Apache-2.0,https://spdx.org/licenses/Apache-2.0,3,3,spdx-license-identifier: apache-2.0,apache-2.0,apache-2.0,,,,,True,,,1-spdx-id,6,6,100.00,100.00,,,,,,,,,,,,,,,,,,,,,,,,,,,
yum-requirements.txt,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,pypi,,,,,,Python,,,,,,,,,,,,,,,,,yum-requirements.txt,,,
```

### How To Reproduce

On Ubuntu 20.04.2 LTS, running scancode 30.1.0 installed with pip3

bash script below:

```bash
$ cat ./scancode-bug1 
#!/usr/bin/env bash
# INPUT(S):
# $1: URL of git repo

rundatetime=$(date -u +%Y%m%dT%H%M%SZ)
tmpdir=$(mktemp -d -t oss-scancode-XXXXXXXX)
ossscanwebdir=/proj/web/infra/oss-check/$0
outdir="$PWD"
mkdir -p "$outdir"
pushd "$tmpdir" || exit
curl -O https://raw.githubusercontent.com/lowRISC/opentitan/master/yum-requirements.txt
curl -O https://raw.githubusercontent.com/lowRISC/opentitan/master/toolchain.txt
head -n 3 *
scancode -l -c -p --strip-root --html "$outdir"/scancode-report.html --json "$outdir"/scancode-report.json --csv "$outdir"/scancode-report.csv .
```

**Comment by pombredanne** [comment]
@kevbroch Thank you
There are thee unrelated issues:

1. the copyright detection where lowRisc is a somewhat uncommon letter case for a name is detected as a plain noun  in the grammar rather than a proper noun.
For reference I get this parse tree when using the SCANCODE_DEBUG_COPYRIGHT=yes env var:
```
DEBUG:cluecode.copyrights:CopyrightDetector: parse_tree: (label='ROOT', children=(
  (label='COPY', value='Copyright')
  (label='NN', value='lowRISC')
  (label='CONTRIBUTORS', value='contributors.')
```
This sequence of tags e.g., COPY NN  CONTRIBUTORS is not a copyright rule. It should and this will cover this case.

2. there are missing license detection rules and this is reported incorrectly:
```
end_line: 2
matched_rule:
    identifier: unknown-license-reference_283.RULE
    license_expression: unknown-license-reference
    licenses:
        - unknown-license-reference
    referenced_filenames:
        - LICENSE
    is_license_text: no
    is_license_notice: no
    is_license_reference: yes
    is_license_tag: no
    is_license_intro: no
    has_unknown: yes
    matcher: 2-aho
    rule_length: 4
    matched_length: 4
    match_coverage: '100.0'
    rule_relevance: 100
matched_text: see LICENSE for details.
```
when using these scan options:
```
            --copyright: yes
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: '-'
```

3. the two detections should be identical in both files whatever these detections are.


Thank you again!


Here are the full details of a scan using the latest develop:


```
headers:
    -   tool_name: scancode-toolkit
        tool_version: 30.1.0
        options:
            input:
                - .
            --copyright: yes
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: '-'
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2022-02-01T192721.838223'
        end_timestamp: '2022-02-01T192723.923185'
        output_format_version: 2.0.0
        duration: '2.084970712661743'
        message:
        errors: []
        extra_data:
            spdx_license_list_version: '3.15'
            OUTDATED: 'WARNING: Outdated ScanCode Toolkit version! You are using an outdated
                version of ScanCode Toolkit: 30.1.0 released on: 2021-09-24. A new version is
                available with important improvements including bug and security fixes, updated
                license, copyright and package detection, and improved scanning accuracy. Please
                download and install the latest version of ScanCode. Visit https://github.com/nexB/scancode-toolkit/releases
                for details.'
            files_count: 3
files:
    -   path: lowrisc
        type: directory
        licenses: []
        license_expressions: []
        percentage_of_license_text: '0'
        copyrights: []
        holders: []
        authors: []
        scan_errors: []
    -   path: lowrisc/origin.ABOUT
        type: file
        licenses: []
        license_expressions: []
        percentage_of_license_text: '0'
        copyrights: []
        holders: []
        authors: []
        scan_errors: []
    -   path: lowrisc/toolchain.txt
        type: file
        licenses:
            -   key: apache-2.0
                score: '73.33'
                name: Apache License 2.0
                short_name: Apache 2.0
                category: Permissive
                is_exception: no
                is_unknown: no
                owner: Apache Software Foundation
                homepage_url: http://www.apache.org/licenses/
                text_url: http://www.apache.org/licenses/LICENSE-2.0
                reference_url: https://scancode-licensedb.aboutcode.org/apache-2.0
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml
                spdx_license_key: Apache-2.0
                spdx_url: https://spdx.org/licenses/Apache-2.0
                start_line: 2
                end_line: 2
                matched_rule:
                    identifier: apache-2.0_464.RULE
                    license_expression: apache-2.0
                    licenses:
                        - apache-2.0
                    referenced_filenames:
                        - LICENSE
                    is_license_text: no
                    is_license_notice: yes
                    is_license_reference: no
                    is_license_tag: no
                    is_license_intro: no
                    has_unknown: no
                    matcher: 3-seq
                    rule_length: 15
                    matched_length: 11
                    match_coverage: '73.33'
                    rule_relevance: 100
                matched_text: Licensed under the Apache License, Version 2.0, see LICENSE for
            -   key: apache-2.0
                score: '100.0'
                name: Apache License 2.0
                short_name: Apache 2.0
                category: Permissive
                is_exception: no
                is_unknown: no
                owner: Apache Software Foundation
                homepage_url: http://www.apache.org/licenses/
                text_url: http://www.apache.org/licenses/LICENSE-2.0
                reference_url: https://scancode-licensedb.aboutcode.org/apache-2.0
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml
                spdx_license_key: Apache-2.0
                spdx_url: https://spdx.org/licenses/Apache-2.0
                start_line: 3
                end_line: 3
                matched_rule:
                    identifier: 'spdx-license-identifier: apache-2.0'
                    license_expression: apache-2.0
                    licenses:
                        - apache-2.0
                    referenced_filenames: []
                    is_license_text: no
                    is_license_notice: no
                    is_license_reference: no
                    is_license_tag: yes
                    is_license_intro: no
                    has_unknown: no
                    matcher: 1-spdx-id
                    rule_length: 6
                    matched_length: 6
                    match_coverage: '100.0'
                    rule_relevance: 100
                matched_text: 'SPDX-License-Identifier: Apache-2.0'
        license_expressions:
            - apache-2.0
            - apache-2.0
        percentage_of_license_text: '10.37'
        copyrights: []
        holders: []
        authors: []
        scan_errors: []
    -   path: lowrisc/yum-requirements.txt
        type: file
        licenses:
            -   key: apache-2.0
                score: '100.0'
                name: Apache License 2.0
                short_name: Apache 2.0
                category: Permissive
                is_exception: no
                is_unknown: no
                owner: Apache Software Foundation
                homepage_url: http://www.apache.org/licenses/
                text_url: http://www.apache.org/licenses/LICENSE-2.0
                reference_url: https://scancode-licensedb.aboutcode.org/apache-2.0
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml
                spdx_license_key: Apache-2.0
                spdx_url: https://spdx.org/licenses/Apache-2.0
                start_line: 2
                end_line: 2
                matched_rule:
                    identifier: apache-2.0_463.RULE
                    license_expression: apache-2.0
                    licenses:
                        - apache-2.0
                    referenced_filenames:
                        - LICENSE
                    is_license_text: no
                    is_license_notice: yes
                    is_license_reference: no
                    is_license_tag: no
                    is_license_intro: no
                    has_unknown: no
                    matcher: 2-aho
                    rule_length: 10
                    matched_length: 10
                    match_coverage: '100.0'
                    rule_relevance: 100
                matched_text: Licensed under the Apache License, Version 2.0, see LICENSE
            -   key: unknown-license-reference
                score: '100.0'
                name: Unknown License file reference
                short_name: Unknown License reference
                category: Unstated License
                is_exception: no
                is_unknown: yes
                owner: Unspecified
                homepage_url:
                text_url:
                reference_url: https://scancode-licensedb.aboutcode.org/unknown-license-reference
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.yml
                spdx_license_key: LicenseRef-scancode-unknown-license-reference
                spdx_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE
                start_line: 2
                end_line: 2
                matched_rule:
                    identifier: unknown-license-reference_283.RULE
                    license_expression: unknown-license-reference
                    licenses:
                        - unknown-license-reference
                    referenced_filenames:
                        - LICENSE
                    is_license_text: no
                    is_license_notice: no
                    is_license_reference: yes
                    is_license_tag: no
                    is_license_intro: no
                    has_unknown: yes
                    matcher: 2-aho
                    rule_length: 4
                    matched_length: 4
                    match_coverage: '100.0'
                    rule_relevance: 100
                matched_text: see LICENSE for details.
            -   key: apache-2.0
                score: '100.0'
                name: Apache License 2.0
                short_name: Apache 2.0
                category: Permissive
                is_exception: no
                is_unknown: no
                owner: Apache Software Foundation
                homepage_url: http://www.apache.org/licenses/
                text_url: http://www.apache.org/licenses/LICENSE-2.0
                reference_url: https://scancode-licensedb.aboutcode.org/apache-2.0
                scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE
                scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml
                spdx_license_key: Apache-2.0
                spdx_url: https://spdx.org/licenses/Apache-2.0
                start_line: 3
                end_line: 3
                matched_rule:
                    identifier: 'spdx-license-identifier: apache-2.0'
                    license_expression: apache-2.0
                    licenses:
                        - apache-2.0
                    referenced_filenames: []
                    is_license_text: no
                    is_license_notice: no
                    is_license_reference: no
                    is_license_tag: yes
                    is_license_intro: no
                    has_unknown: no
                    matcher: 1-spdx-id
                    rule_length: 6
                    matched_length: 6
                    match_coverage: '100.0'
                    rule_relevance: 100
                matched_text: 'SPDX-License-Identifier: Apache-2.0'
        license_expressions:
            - apache-2.0
            - unknown-license-reference
            - apache-2.0
        percentage_of_license_text: '13.95'
        copyrights: []
        holders: []
        authors: []
        scan_errors: []

```
