### ISSUE TITLE
False positive SSPL license detection

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2975]
`#define PEX_ROOT_CMPLX_SSPL_REG(if)    ((MV_PEX_IF_REGS_BASE(if)) + 0x1A0C)` gets detected incorrectly this way:
```
licenses:
    -   key: mongodb-sspl-1.0
        score: '90.0'
        name: Server Side Public License (SSPL) 1.0
        short_name: SSPL 1.0
        category: Source-available
        is_exception: no
        is_unknown: no
        owner: MongoDB
        homepage_url: https://www.mongodb.com/licensing/server-side-public-license
        text_url:
        reference_url: https://scancode-licensedb.aboutcode.org/mongodb-sspl-1.0
        scancode_text_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mongodb-sspl-1.0.LICENSE
        scancode_data_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mongodb-sspl-1.0.yml
        spdx_license_key: SSPL-1.0
        spdx_url: https://spdx.org/licenses/SSPL-1.0
        start_line: 1
        end_line: 1
        matched_rule:
            identifier: mongodb-sspl-1.0_60.RULE
            license_expression: mongodb-sspl-1.0
            licenses:
                - mongodb-sspl-1.0
            referenced_filenames: []
            is_license_text: no
            is_license_notice: no
            is_license_reference: yes
            is_license_tag: no
            is_license_intro: no
            has_unknown: no
            matcher: 2-aho
            rule_length: 1
            matched_length: 1
            match_coverage: '100.0'
            rule_relevance: 90
        matched_text: SSPL_
license_expressions:
    - mongodb-sspl-1.0
```
