### ISSUE TITLE
NuGet package party types is missing

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2991]
See https://github.com/nexB/scancode-toolkit/issues/2989
```
parties:
            -   type:
                role: author
                name: Sam Saffron,Marc Gravell,Nick Craver
                email:
                url:
            -   type:
                role: owner
                name: Sam Saffron,Marc Gravell,Nick Craver
                email:
                url:

```

is missing a party type
