### ISSUE TITLE
Use libxml2 as a test for the new "license detection"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3112]
https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.7.8/libxml2-v2.7.8.tar.gz is a good test as this is a common library annd it has many files with this notice "See Copyright for the status of this software." matched to https://github.com/nexB/scancode-toolkit/blob/6007301cca4eff424202abf197467ee2f004e139/src/licensedcode/data/rules/unknown-license-reference_30.yml
```yaml
license_expression: unknown-license-reference
is_license_reference: yes
relevance: 100
referenced_filenames:
    - Copyright
```
This is a file reference to https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/Copyright which is a https://scancode-licensedb.aboutcode.org/x11-xconsortium-veillard.html

This is also an odd ball since it declares itself as MIT-license but this is closely related but not a standard MIT license
