### ISSUE TITLE
MISDETECTION GPL-3.0-or-later detected as GPL-1.0-or-later

### ISSUE THREAD

**Issue by eclipseo** [nexB/scancode-toolkit#3499]
The file is: https://raw.githubusercontent.com/ellejohara/newretrograde/master/NewRetrograde.qml

It has the following header:

```
//===========================================================================
// New Retrograde
// https://github.com/ellejohara/newretrograde
// 
// Copyright (C) 2020 Astrid Lydia Johannsen (ellejohara)
// 
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 3
//  as published by the Free Software Foundation and appearing in
//  the file LICENSE
//===========================================================================
```

So it is GPL-3.0-or-later.

`$ scancode -l --license-text --license-text-diagnostics --yaml error.yml NewRetrograde.qml`

We get:

```
headers:
    -   tool_name: scancode-toolkit
        tool_version: 32.0.6
        options:
            input:
                - NewRetrograde.qml
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: error.yml
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2023-08-27T100423.764693'
        end_timestamp: '2023-08-27T100426.385427'
        output_format_version: 3.0.0
        duration: '2.6207454204559326'
        message:
        errors: []
        warnings: []
        extra_data:
            system_environment:
                operating_system: linux
                cpu_architecture: 64
                platform: Linux-6.4.12-200.fc38.x86_64-x86_64-with-glibc2.37
                platform_version: '#1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023'
                python_version: 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red
                    Hat 13.1.1-2)]
            spdx_license_list_version: '3.21'
            files_count: 1
license_detections:
    -   identifier: gpl_1_0_plus-1aea2ef4-b0a1-43d7-99d5-df85d8e64470
        license_expression: gpl-1.0-plus
        detection_count: 1
files:
    -   path: NewRetrograde.qml
        type: file
        detected_license_expression: gpl-1.0-plus
        detected_license_expression_spdx: GPL-1.0-or-later
        license_detections:
            -   license_expression: gpl-1.0-plus
                matches:
                    -   score: '97.06'
                        start_line: 7
                        end_line: 10
                        matched_length: 33
                        match_coverage: '97.06'
                        matcher: 3-seq
                        license_expression: gpl-1.0-plus
                        rule_identifier: gpl_15.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl_15.RULE
                        matched_text: |
                            This program is free software; you can redistribute it and/or modify
                            //  it under the terms of the GNU General Public License [version] [3]
                            //  as published by the Free Software Foundation [and] [appearing] in
                            //  the file LICENSE
                identifier: gpl_1_0_plus-1aea2ef4-b0a1-43d7-99d5-df85d8e64470
        license_clues: []
        percentage_of_license_text: '7.3'
        scan_errors: []
```

The rule: https://raw.githubusercontent.com/nexB/scancode-toolkit/develop/src/licensedcode/data/rules/gpl_15.RULE

```
---
license_expression: gpl-1.0-plus
is_license_notice: yes
notes: BCM GPL notice
---

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, located in the file LICENSE.
```

The score is high, but the "version 3" in the text should prevent it to be matched by gpl_15.RULE.

**Comment by eclipseo** [comment]
I have multiple repro of this: https://raw.githubusercontent.com/musescore/MuseScore/v4.1.1/src/framework/uicomponents/view/selectmultipledirectoriesmodel.cpp

```
//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  Copyright (C) 2021 MuseScore BVBA and others
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//=============================================================================
```

`$ scancode -l --license-text --license-text-diagnostics --yaml error.yml selectmultipledirectoriesmodel.cpp`


```
headers:
    -   tool_name: scancode-toolkit
        tool_version: 32.0.6
        options:
            input:
                - selectmultipledirectoriesmodel.cpp
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: error.yml
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2023-08-27T101052.974428'
        end_timestamp: '2023-08-27T101055.623312'
        output_format_version: 3.0.0
        duration: '2.648893117904663'
        message:
        errors: []
        warnings: []
        extra_data:
            system_environment:
                operating_system: linux
                cpu_architecture: 64
                platform: Linux-6.4.12-200.fc38.x86_64-x86_64-with-glibc2.37
                platform_version: '#1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023'
                python_version: 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red
                    Hat 13.1.1-2)]
            spdx_license_list_version: '3.21'
            files_count: 1
license_detections:
    -   identifier: gpl_2_0_and_gpl_1_0_plus_and_other_copyleft-01cccaa9-5b7f-af9e-7894-a5b481c8648b
        license_expression: gpl-2.0 AND gpl-1.0-plus AND other-copyleft
        detection_count: 1
files:
    -   path: selectmultipledirectoriesmodel.cpp
        type: file
        detected_license_expression: gpl-2.0 AND gpl-1.0-plus AND other-copyleft
        detected_license_expression_spdx: GPL-2.0-only AND GPL-1.0-or-later AND LicenseRef-scancode-other-copyleft
        license_detections:
            -   license_expression: gpl-2.0 AND gpl-1.0-plus AND other-copyleft
                matches:
                    -   score: '100.0'
                        start_line: 7
                        end_line: 8
                        matched_length: 24
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: gpl-2.0
                        rule_identifier: gpl-2.0_541.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-2.0_541.RULE
                        matched_text: |
                            This program is free software; you can redistribute it and/or modify
                            //  it under the terms of the GNU General Public License version 2.
                    -   score: '100.0'
                        start_line: 10
                        end_line: 13
                        matched_length: 37
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: gpl-1.0-plus
                        rule_identifier: gpl_28.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl_28.RULE
                        matched_text: |
                            This program is distributed in the hope that it will be useful,
                            //  but WITHOUT ANY WARRANTY; without even the implied warranty of
                            //  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
                            //  GNU General Public License for more details.
                    -   score: '100.0'
                        start_line: 15
                        end_line: 16
                        matched_length: 15
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: gpl-1.0-plus
                        rule_identifier: gpl-1.0-plus_34.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-1.0-plus_34.RULE
                        matched_text: |
                            You should have received a copy of the GNU General Public License
                            //  along with this program;
                    -   score: '90.0'
                        start_line: 16
                        end_line: 17
                        matched_length: 11
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: other-copyleft
                        rule_identifier: other-copyleft_fsf_address_2.RULE
                        rule_relevance: 90
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/other-copyleft_fsf_address_2.RULE
                        matched_text: |
                            Free Software
                            //  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
                identifier: gpl_2_0_and_gpl_1_0_plus_and_other_copyleft-01cccaa9-5b7f-af9e-7894-a5b481c8648b
        license_clues: []
        percentage_of_license_text: '18.28'
        scan_errors: []

```

Here the detection are "correct" wrt the rules,.
