### ISSUE TITLE
"Contains no GPLed code" wrongly interpreted as GPL-1.0-or-later

### ISSUE THREAD

**Issue by stefan6419846** [nexB/scancode-toolkit#3509]
### Description

https://github.com/django/django/blob/4.2.5/django/utils/baseconv.py is being wrongly detected as being `Python-2.0 AND GPL-1.0-or-later`, although it explicitly states:

> This Baseconv distribution contains no GNU General Public Licensed (GPLed) code so it may be used in proprietary projects just like prior ``baseconv`` distributions.

### How To Reproduce

* `wget https://github.com/django/django/raw/4.2.5/django/utils/baseconv.py`
* `scancode -l --license-text --license-text-diagnostics --yaml error.yml baseconv.py`
* `cat error.yml`

### Result

```yaml
headers:
    -   tool_name: scancode-toolkit
        tool_version: 32.0.6
        options:
            input:
                - baseconv.py
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: error.yml
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2023-09-14T105045.567838'
        end_timestamp: '2023-09-14T105048.044637'
        output_format_version: 3.0.0
        duration: '2.4768130779266357'
        message:
        errors: []
        warnings: []
        extra_data:
            system_environment:
                operating_system: linux
                cpu_architecture: 64
                platform: Linux-5.14.21-150400.24.81-default-x86_64-with-glibc2.31
                platform_version: '#1 SMP PREEMPT_DYNAMIC Tue Aug 8 14:10:43 UTC 2023 (90a74a8)'
                python_version: 3.9.17 (main, Jul 01 2023, 21:18:10) [GCC]
            spdx_license_list_version: '3.21'
            files_count: 1
license_detections:
    -   identifier: gpl_1_0_plus-3fed9292-c205-6060-aba8-d1a8ba5deddf
        license_expression: gpl-1.0-plus
        detection_count: 1
    -   identifier: python-e39bbc28-5906-3d85-f472-b3bba199a908
        license_expression: python
        detection_count: 1
files:
    -   path: baseconv.py
        type: file
        detected_license_expression: python AND gpl-1.0-plus
        detected_license_expression_spdx: Python-2.0 AND GPL-1.0-or-later
        license_detections:
            -   license_expression: python
                matches:
                    -   score: '100.0'
                        start_line: 6
                        end_line: 7
                        matched_length: 7
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: python
                        rule_identifier: python_17.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/python_17.RULE
                        matched_text: |
                            License:
                            #   Python Software Foundation License version 2
                identifier: python-e39bbc28-5906-3d85-f472-b3bba199a908
            -   license_expression: gpl-1.0-plus
                matches:
                    -   score: '100.0'
                        start_line: 12
                        end_line: 12
                        matched_length: 1
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: gpl-1.0-plus
                        rule_identifier: gpl-1.0-plus_64.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-1.0-plus_64.RULE
                        matched_text: GPLed)
                identifier: gpl_1_0_plus-3fed9292-c205-6060-aba8-d1a8ba5deddf
        license_clues: []
        percentage_of_license_text: '2.19'
        scan_errors: []

```

### System configuration

OpenSUSE Leap 15.4, running Python 3.9 with `scancode-toolkit==32.0.6`, installed from PIP
