### ISSUE TITLE
incorrect SPDX key for unknown-license-reference/unknown-license-reference_225.RULE

### ISSUE THREAD

**Issue by lalitbittu11** [nexB/scancode-toolkit#3574]
Dear Developers,

we are getting incorrect spdx identifier for license "unknown-license-reference" against the rule - unknown-license-reference_225.RULE in scancode-toolkit version v32.0.8.
is this expected? previous version is providing spdx key value for the same rule as - "LicenseRef-scancode-unknown-license-reference".

{
      "path": "files/zlib-1.2.11/zlib-1.2.11/contrib/dotzlib/readme.txt",
      "type": "file",
      "package_data": [],
      "for_packages": [
        "pkg:autotools/zlib-1.2.11?uuid=df7b94fe-9356-4ce3-8250-bc1617006f11"
      ],
      "detected_license_expression": "boost-1.0",
      "detected_license_expression_spdx": "BSL-1.0",
      "license_detections": [
        {
          "license_expression": "boost-1.0",
          "matches": [
            {
              "score": 100.0,
              "start_line": 10,
              "end_line": 10,
              "matched_length": 6,
              "match_coverage": 100.0,
              "matcher": "2-aho",
              "license_expression": "unknown-license-reference",
              "rule_identifier": "unknown-license-reference_225.RULE",
              "rule_relevance": 100,
              "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown-license-reference_225.RULE",
              "matched_text": "LICENSE_1_0.txt       - License file." 

Regards
Lalit

**Comment by pombredanne** [comment]
@lalitbittu11 Thanks for the report... I am getting the same data as you have and the  "license detection" section is correct: it does follow the unknown license reference to the license text in LICENSE_1_0.txt and assigns the Boost license correctly from what I can see?

You should look at detections, not only lower level matches. The whole point of "detections" is to improve massively the quality of licensing  by combining lower level matches.


I am getting this with this zip
[zlib-contrib-dotzib-1.2.11.zip](https://github.com/nexB/scancode-toolkit/files/13307095/zlib-contrib-dotzib-1.2.11.zip)
```YAML
    -   path: zlib-contrib-dotzib-1.2.11.zip-extract/zlib-1.2.11/contrib/dotzlib/readme.txt
        type: file
        detected_license_expression: boost-1.0
        detected_license_expression_spdx: BSL-1.0
        license_detections:
            -   license_expression: boost-1.0
                matches:
                    -   score: '100.0'
                        start_line: 10
                        end_line: 10
                        matched_length: 6
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: unknown-license-reference
                        rule_identifier: unknown-license-reference_225.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown-license-reference_225.RULE
                        matched_text: LICENSE_1_0.txt       - License file.
                    -   score: '100.0'
                        start_line: 1
                        end_line: 23
                        matched_length: 211
                        match_coverage: '100.0'
                        matcher: 1-hash
                        license_expression: boost-1.0
                        rule_identifier: boost-1.0.LICENSE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/boost-1.0.LICENSE
                        matched_text: "Boost Software License - Version 1.0 - August 17th, 2003\r\
                            \n\r\nPermission is hereby granted, free of charge, to any person\
                            \ or organization\r\nobtaining a copy of the software and accompanying\
                            \ documentation covered by\r\nthis license (the \"Software\") to\
                            \ use, reproduce, display, distribute,\r\nexecute, and transmit\
                            \ the Software, and to prepare derivative works of the\r\nSoftware,\
                            \ and to permit third-parties to whom the Software is furnished\
                            \ to\r\ndo so, all subject to the following:\r\n\r\nThe copyright\
                            \ notices in the Software and this entire statement, including\r\
                            \nthe above license grant, this restriction and the following disclaimer,\r\
                            \nmust be included in all copies of the Software, in whole or in\
                            \ part, and\r\nall derivative works of the Software, unless such\
                            \ copies or derivative\r\nworks are solely in the form of machine-executable\
                            \ object code generated by\r\na source language processor.\r\n\r\
                            \nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\
                            \ EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\
                            \ OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE, TITLE\
                            \ AND NON-INFRINGEMENT. IN NO EVENT\r\nSHALL THE COPYRIGHT HOLDERS\
                            \ OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\r\nFOR ANY DAMAGES\
                            \ OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\r\n\
                            ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE\
                            \ OR OTHER\r\nDEALINGS IN THE SOFTWARE."
                identifier: boost_1_0-5cff8c89-be8c-7d4a-7989-c20725314b4c
                detection_log:
                    - unknown-reference-to-local-file
            -   license_expression: boost-1.0
                matches:
                    -   score: '100.0'
                        start_line: 57
                        end_line: 58
                        matched_length: 32
                        match_coverage: '100.0'
                        matcher: 2-aho
                        license_expression: boost-1.0
                        rule_identifier: boost-1.0_21.RULE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/boost-1.0_21.RULE
                        matched_text: "Use, modification and distribution are subject to the\
                            \ Boost Software License, Version 1.0.\r\n(See accompanying file\
                            \ LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)"
                    -   score: '100.0'
                        start_line: 1
                        end_line: 23
                        matched_length: 211
                        match_coverage: '100.0'
                        matcher: 1-hash
                        license_expression: boost-1.0
                        rule_identifier: boost-1.0.LICENSE
                        rule_relevance: 100
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/boost-1.0.LICENSE
                        matched_text: "Boost Software License - Version 1.0 - August 17th, 2003\r\
                            \n\r\nPermission is hereby granted, free of charge, to any person\
                            \ or organization\r\nobtaining a copy of the software and accompanying\
                            \ documentation covered by\r\nthis license (the \"Software\") to\
                            \ use, reproduce, display, distribute,\r\nexecute, and transmit\
                            \ the Software, and to prepare derivative works of the\r\nSoftware,\
                            \ and to permit third-parties to whom the Software is furnished\
                            \ to\r\ndo so, all subject to the following:\r\n\r\nThe copyright\
                            \ notices in the Software and this entire statement, including\r\
                            \nthe above license grant, this restriction and the following disclaimer,\r\
                            \nmust be included in all copies of the Software, in whole or in\
                            \ part, and\r\nall derivative works of the Software, unless such\
                            \ copies or derivative\r\nworks are solely in the form of machine-executable\
                            \ object code generated by\r\na source language processor.\r\n\r\
                            \nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\
                            \ EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\
                            \ OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE, TITLE\
                            \ AND NON-INFRINGEMENT. IN NO EVENT\r\nSHALL THE COPYRIGHT HOLDERS\
                            \ OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\r\nFOR ANY DAMAGES\
                            \ OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\r\n\
                            ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE\
                            \ OR OTHER\r\nDEALINGS IN THE SOFTWARE."
                identifier: boost_1_0-d2497bb7-4937-90c9-b38e-63d81d1b1d13
                detection_log:
                    - unknown-reference-to-local-file
        license_clues: []
        percentage_of_license_text: '11.18'
        scan_errors: []


```

Full scan:
[zlib-contrib-dotzib-1.2.11.zip-scancode.yaml.txt](https://github.com/nexB/scancode-toolkit/files/13307094/zlib-contrib-dotzib-1.2.11.zip-scancode.yaml.txt)
