### ISSUE TITLE
Got "CC-BY-NC-SA-3.0 AND CC-BY-SA-3.0" for file mentioning elements under CC-BY-SA-3.0

### ISSUE THREAD

**Issue by camillem** [nexB/scancode-toolkit#3615]
### Description

Not sure if this is a bug, but an issue, at least for me. 
When scanning the attached `custom-content.html` file (attached) , I get "CC-BY-NC-SA-3.0 AND CC-BY-SA-3.0" for `detected_license_expression_spdx`, while the content only refers to elements under CC-BY-SA-3.0. (see attached json file)

### How To Reproduce

```bash
git checkout v32.0.8
./configure
source venv/bin/activate
scancode -h
scancode --license --copyright --json-pp scancode_result.json custom-content.html 
```

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Ubuntu 22.04.3 LTS
* What version of scancode-toolkit was used to generate the scan file?  v32.0.8
* What installation method was used to install/run scancode? source download

[custom-content.html.txt](https://github.com/nexB/scancode-toolkit/files/13529627/custom-content.html.txt)

[scancode_result.json](https://github.com/nexB/scancode-toolkit/files/13529622/scancode_result.json)

**Comment by pombredanne** [comment]
Thanks for the report. I will make a dedicated fix commit to show what the simple fix is FWIW.

**Comment by dotarjun** [comment]
Hey do you mind if I give this a shot?

**Comment by pombredanne** [comment]
@dotarjun sure thing! please do and thank you.

**Comment by pombredanne** [comment]
@dotarjun here is a change that may fix things:
In `src/licensedcode/data/rules/cc-by-nc-sa-3.0_22.RULE` add double curly braces to make a part a "key phrase":

```YAML
---
license_expression: cc-by-nc-sa-3.0
is_license_notice: yes
relevance: 100
ignorable_urls:
    - http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US
---

This book is licensed under a Creative Commons 
http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US [{{Attribution-NonCommercial-ShareAlike 3.0}} Unported] license. 
For more information, please see the Creative Commons page.
```
