### ISSUE TITLE
Missing copyright from LICENSE file (ngx-bootstrap:6.1.0)

### ISSUE THREAD

**Issue by vw-anton** [nexB/scancode-toolkit#3655]
### Description
Scancode is not detecting all copyrights in this file: 
https://github.com/valor-software/ngx-bootstrap/blob/e1a0bb8cbf83eb717335f1d74f995adc6dde60c0/src/chronos/LICENSE

Output: 
```
Copyright (c) Valor Software
Copyright (c) Dmitriy Shekhovtsov<valorkin@gmail.com>
Copyright (c) JS Foundation and other contributors
```

Expected output: 
```
Copyright (c) Valor Software
Copyright (c) Dmitriy Shekhovtsov<valorkin@gmail.com>
Copyright (c) moment/moment                                    <-- missing
Copyright (c) JS Foundation and other contributors
```

### How To Reproduce

ScanCode via ORT: 

```
  scanner:
      name: "ScanCode"
      version: "32.0.8"
      configuration: "--copyright --license --info --strip-root --timeout 300 --json-pp"
```

See also attached run from scancode.io - same result
[scancodeio_ngx-bootstrap-6.1.0.json](https://github.com/nexB/scancode-toolkit/files/14294199/scancodeio_ngx-bootstrap-6.1.0.json)

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)

Linux

* What version of scancode-toolkit was used to generate the scan file?

ScanCode 32.0.8

* What installation method was used to install/run scancode? (pip/source download/other)

ORT embedded
