### ISSUE TITLE
TypeError while scanning file (PDF)

### ISSUE THREAD

**Issue by vw-anton** [nexB/scancode-toolkit#3794]
### Description

When scanning a PDF from https://github.com/hopding/pdf-lib (rev 4beebbef7a261ed0be089bb1d63a5b6e28cc488a) we receive: 

> TypeError while scanning file 'assets/pdfs/with_invalid_objects.pdf' (int() argument must be a string, a bytes-like object or a real number, not 'PSKeyword'

### How To Reproduce

ScanCode 32.1.0 via ORT (22.5.0)

```
 config:
      ScanCode:
        options:
          commandLine: "--copyright --license --license-text --info --strip-root --timeout\
            \ 600"
          parseLicenseExpressions: "true"
```

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)
  * Linux
* What version of scancode-toolkit was used to generate the scan file?
  * 32.1.0
* What installation method was used to install/run scancode? (pip/source download/other)
  * pip in ORT

**Comment by pombredanne** [comment]
@vw-anton Thanks for the report! This is likely a bug in the underlying PDF library. Do you have a full stack trace?

**Comment by vw-anton** [comment]
From ORT we only received 
```
  issues:
      - timestamp: "2024-06-06T08:26:01.748905945Z"
        source: "ScanCode"
        message: "ERROR: TypeError while scanning file 'assets/pdfs/with_invalid_objects.pdf'\
          \ (int() argument must be a string, a bytes-like object or a real number,\
          \ not 'PSKeyword')."
        severity: "ERROR"
```

I ran this via scancode.io but in the exported JSON I cannot see any indicator, the the console logs too.
