### ISSUE TITLE
Multiline copyright missing from license file

### ISSUE THREAD

**Issue by vw-anton** [nexB/scancode-toolkit#3796]
### Description

We found a package where author/copyright information is missing from a license file. 
It looks like only the first author of a list is represented in the scan result.

### How To Reproduce

https://github.com/formidablelabs/victory.git 
commit dd86278d205f3f306e2ab38c317a6f9c56f0a6f8 

Copyrights found:
```
 copyrights:
      - statement: "Copyright (c) 2014-present, Facebook, Inc."
        location:
          path: "packages/victory-core/src/victory-util/immutable-types.d.ts"
          start_line: 2
          end_line: 2
      - statement: "Copyright (c) 2015-2020 Formidable Labs"
        location:
          path: "LICENSE.txt"
          start_line: 3
          end_line: 3
      - statement: "Copyright (c) 2016-2020 Alexey Svetliakov <https://github.com/asvetliakov>"
        location:
          path: "LICENSE.txt"
          start_line: 5
          end_line: 5
```

However in the **LICENSE.txt** file we can see: 
```
Copyright (c) 2016-2020 Alexey Svetliakov <https://github.com/asvetliakov>,
snerks <https://github.com/snerks>, Krzysztof Cebula <https://github.com
Havret>, Vitaliy Polyanskiy <https://github.com/alreadyExisted>, James Lismore
<https://github.com/jlismore>, Stack Builders <https://github.com
stackbuilders>, Esteban Ibarra <https://github.com/ibarrae>, Dominic Lee
<https://github.com/dominictwlee>, Dave Vedder <https://github.com
veddermatic>, Alec Flett <https://github.com/alecf> and potentially other
DefinitelyTyped contributors.
```

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
  * Linux 
* What version of scancode-toolkit was used to generate the scan file?
  * 32.1.0 
* What installation method was used to install/run scancode? (pip/source download/other)
  * Python (via ORT 22.5.0)
