### ISSUE TITLE
MIT reported as "GPL-3.0-or-later OR MIT"

### ISSUE THREAD

**Issue by stefan6419846** [nexB/scancode-toolkit#3860]
### Description

https://github.com/jborean93/pyspnego/blob/main/src/spnego/_context.py is wrongly being detected as being `(GPL-3.0-or-later OR MIT) AND LicenseRef-scancode-unknown-license-reference`, where especially the GPL detection is wrong.

### How To Reproduce

* `wget https://github.com/jborean93/pyspnego/raw/2811a7ea7f99866b0b99cb16892b42d66b739fe5/src/spnego/_context.py`
* `scancode -l --license-text --license-text-diagnostics --yaml error.yml _context.py`
* `cat error.yml`

### Result

```yaml
headers:
    -   tool_name: scancode-toolkit
        tool_version: 32.2.0
        options:
            input:
                - _context.py
            --license: yes
            --license-text: yes
            --license-text-diagnostics: yes
            --yaml: error.yml
        notice: |
            Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
            OR CONDITIONS OF ANY KIND, either express or implied. No content created from
            ScanCode should be considered or used as legal advice. Consult an Attorney
            for any legal advice.
            ScanCode is a free software code scanning tool from nexB Inc. and others.
            Visit https://github.com/nexB/scancode-toolkit/ for support and download.
        start_timestamp: '2024-07-15T063513.618264'
        end_timestamp: '2024-07-15T063519.279102'
        output_format_version: 3.2.0
        duration: '5.660857200622559'
        message:
        errors: []
        warnings: []
        extra_data:
            system_environment:
                operating_system: linux
                cpu_architecture: 64
                platform: Linux-5.14.21-150400.24.100-default-x86_64-with-glibc2.31
                platform_version: '#1 SMP PREEMPT_DYNAMIC Mon Dec 4 19:12:13 UTC 2023 (3f5cd84)'
                python_version: 3.9.18 (main, Sep 06 2023, 07:49:32) [GCC]
            spdx_license_list_version: '3.24'
            files_count: 1
license_detections:
    -   identifier: gpl_3_0_plus_or_mit__and_unknown_license_reference-29b8b9b5-9546-47bf-bd90-de84bbc19431
        license_expression: (gpl-3.0-plus OR mit) AND unknown-license-reference
        license_expression_spdx: (GPL-3.0-or-later OR MIT) AND LicenseRef-scancode-unknown-license-reference
        detection_count: 1
        reference_matches:
            -   license_expression: gpl-3.0-plus OR mit
                license_expression_spdx: GPL-3.0-or-later OR MIT
                from_file: _context.py
                start_line: 2
                end_line: 2
                matcher: 3-seq
                score: '13.46'
                matched_length: 7
                match_coverage: '13.46'
                rule_relevance: 100
                rule_identifier: gpl-3.0-plus_or_mit_8.RULE
                rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-3.0-plus_or_mit_8.RULE
                matched_text: '# MIT License (see LICENSE or https://opensource.org/licenses/MIT)'
                matched_text_diagnostics: License ([see] LICENSE [or] https://opensource.org/licenses/MIT)
            -   license_expression: unknown-license-reference
                license_expression_spdx: LicenseRef-scancode-unknown-license-reference
                from_file: _context.py
                start_line: 2
                end_line: 2
                matcher: 2-aho
                score: '100.0'
                matched_length: 2
                match_coverage: '100.0'
                rule_relevance: 100
                rule_identifier: unknown-license-reference_see-license_1.RULE
                rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown-license-reference_see-license_1.RULE
                matched_text: '# MIT License (see LICENSE or https://opensource.org/licenses/MIT)'
                matched_text_diagnostics: see LICENSE
files:
    -   path: _context.py
        type: file
        detected_license_expression: (gpl-3.0-plus OR mit) AND unknown-license-reference
        detected_license_expression_spdx: (GPL-3.0-or-later OR MIT) AND LicenseRef-scancode-unknown-license-reference
        license_detections:
            -   license_expression: (gpl-3.0-plus OR mit) AND unknown-license-reference
                license_expression_spdx: (GPL-3.0-or-later OR MIT) AND LicenseRef-scancode-unknown-license-reference
                matches:
                    -   license_expression: gpl-3.0-plus OR mit
                        spdx_license_expression: GPL-3.0-or-later OR MIT
                        from_file: _context.py
                        start_line: 2
                        end_line: 2
                        matcher: 3-seq
                        score: '13.46'
                        matched_length: 7
                        match_coverage: '13.46'
                        rule_relevance: 100
                        rule_identifier: gpl-3.0-plus_or_mit_8.RULE
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-3.0-plus_or_mit_8.RULE
                        matched_text: '# MIT License (see LICENSE or https://opensource.org/licenses/MIT)'
                        matched_text_diagnostics: License ([see] LICENSE [or] https://opensource.org/licenses/MIT)
                    -   license_expression: unknown-license-reference
                        spdx_license_expression: LicenseRef-scancode-unknown-license-reference
                        from_file: _context.py
                        start_line: 2
                        end_line: 2
                        matcher: 2-aho
                        score: '100.0'
                        matched_length: 2
                        match_coverage: '100.0'
                        rule_relevance: 100
                        rule_identifier: unknown-license-reference_see-license_1.RULE
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown-license-reference_see-license_1.RULE
                        matched_text: '# MIT License (see LICENSE or https://opensource.org/licenses/MIT)'
                        matched_text_diagnostics: see LICENSE
                identifier: gpl_3_0_plus_or_mit__and_unknown_license_reference-29b8b9b5-9546-47bf-bd90-de84bbc19431
        license_clues: []
        percentage_of_license_text: '0.19'
        scan_errors: []

```

### System configuration

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 32.2.0
* What installation method was used to install/run scancode? pip
