### ISSUE TITLE
Add Cognitive Computation Group license from University of Illinois at Urbana-Champaign

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#4113]
See:
- https://raw.githubusercontent.com/CogComp/cogcomp-nlp/refs/heads/master/LICENSE
This is detected incorrectly as a mix of unknown, permissive and proprietary

Reported by: @yegor256

ScanCode.io detection tab gives these:
```YAML
Detected license expression

    unknown-license-reference AND other-permissive

Detected license expression (SPDX)

    LicenseRef-scancode-unknown-license-reference AND LicenseRef-scancode-other-permissive

License detections

    - matches:
        - score: '20.51'
          matcher: 3-seq
          end_line: 14
          rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown-license-reference_275.RULE
          from_file: codebase/LICENSE
          start_line: 14
          matched_text: WARRANTY OF MERCHANTABILITY AND WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE,
          match_coverage: '20.51'
          matched_length: 8
          rule_relevance: 100
          rule_identifier: unknown-license-reference_275.RULE
          license_expression: unknown-license-reference
          license_expression_spdx: LicenseRef-scancode-unknown-license-reference
        - score: '6.82'
          matcher: 3-seq
          end_line: 15
          rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/other-permissive_119.RULE
          from_file: codebase/LICENSE
          start_line: 15
          matched_text: liable for any direct, indirect, consequential, or incidental damages
          match_coverage: '6.82'
          matched_length: 6
          rule_relevance: 100
          rule_identifier: other-permissive_119.RULE
          license_expression: other-permissive
          license_expression_spdx: LicenseRef-scancode-other-permissive
      identifier: unknown_license_reference_and_other_permissive-b1c5f0ab-8ef9-da2e-a155-15966c61cbbc
      license_expression: unknown-license-reference AND other-permissive
      license_expression_spdx: LicenseRef-scancode-unknown-license-reference AND LicenseRef-scancode-other-permissive

License clues

    - score: '100.0'
      matcher: 2-aho
      end_line: 13
      rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/proprietary-license_272.RULE
      from_file: codebase/LICENSE
      start_line: 13
      matched_text: commercial use
      match_coverage: '100.0'
      matched_length: 2
      rule_relevance: 100
      rule_identifier: proprietary-license_272.RULE
      license_expression: proprietary-license
      license_expression_spdx: LicenseRef-scancode-proprietary-license
    - score: '100.0'
      matcher: 2-aho
      end_line: 13
      rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/proprietary-license_272.RULE
      from_file: codebase/LICENSE
      start_line: 13
      matched_text: commercial use.
      match_coverage: '100.0'
      matched_length: 2
      rule_relevance: 100
      rule_identifier: proprietary-license_272.RULE
      license_expression: proprietary-license
      license_expression_spdx: LicenseRef-scancode-proprietary-license

```
