### ISSUE TITLE
License detection issue in https://github.com/kulshekhar/ts-jest

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#4221]
We are encountering a similar problem with [ts-jest](https://github.com/kulshekhar/ts-jest) incorrectly including a `LicenseRef-scancode-free-unknown` reference. This [line](https://github.com/kulshekhar/ts-jest/blame/v29.1.5/README.md#L69) (specifically `open source license`) seems to be the culprit.

_Originally posted by @tyllark in https://github.com/aboutcode-org/scancode-toolkit/issues/4182#issuecomment-2762425940_

**Comment by pombredanne** [comment]
The scan or the README.md file yields this:
```
files:
    -   path: README.md
        type: file
        package_data: []
        for_packages: []
        detected_license_expression: free-unknown AND mit
        detected_license_expression_spdx: LicenseRef-scancode-free-unknown AND MIT
        license_detections:
            -   license_expression: free-unknown AND mit
                license_expression_spdx: LicenseRef-scancode-free-unknown AND MIT
                matches:
                    -   license_expression: free-unknown
                        license_expression_spdx: LicenseRef-scancode-free-unknown
                        from_file: README.md
                        start_line: 70
                        end_line: 70
                        matcher: 2-aho
                        score: '50.0'
                        matched_length: 3
                        match_coverage: '100.0'
                        rule_relevance: 50
                        rule_identifier: free-unknown_88.RULE
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/free-unknown_88.RULE
                        matched_text: '- [JetBrains](https://www.jetbrains.com/?from=ts-jest)
                            has been kind enough to support ts-jest with an [open source license](https://www.jetbrains.com/community/opensource/?from=ts-jest).'
                        matched_text_diagnostics: open source license](
                    -   license_expression: mit
                        license_expression_spdx: MIT
                        from_file: README.md
                        start_line: 72
                        end_line: 74
                        matcher: 3-seq
                        score: '80.0'
                        matched_length: 12
                        match_coverage: '80.0'
                        rule_relevance: 100
                        rule_identifier: mit_464.RULE
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/mit_464.RULE
                        matched_text: |
                            ## License

                            This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details
                        matched_text_diagnostics: |
                            License

                            This project is licensed under the MIT License - see the [LICENSE.
                identifier: free_unknown_and_mit-15da2979-e9a8-3f7a-a8c7-f5d526560373
```

I filed https://github.com/kulshekhar/ts-jest/pull/4772 and we can fix this here with a false positive rule looking like this:
```
---
is_false_positive: yes
notes: Not a license
---
support ts-jest with an open source license
```
