### ISSUE TITLE
Incorrect license match post-processing for detections

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#4352]
This 
```
TourDeFlex Subcomponents:

The Apache Tour De Flex includes a number of subcomponents with
separate copyright notices and license terms. Your use of the source
code for the these subcomponents is subject to the terms and
conditions of the following licenses. 

The Open-Sans font is available under Apache License 2.0. For details
see TourDeFlex3/src/effects/assets.

The ping sound effect (ping.mp3) in TourDeFlex3/src/effects/assets is licensed
under Creative Commons 3.0. The original file can be found here:
http://www.freesound.org/people/cameronmusic/sounds/138420/

```

 .... leads to these detections:

[foo.yaml.txt](https://github.com/user-attachments/files/20147773/foo.yaml.txt)

... and I think these may not be entirely correct when the unknown reference is then patched/merged with the following single Apache? But we also have a (weak) CC-BY

`licensed under Creative Commons 3.0.` is not detected correctly either

**Comment by pombredanne** [comment]
Actually this is a false alarm. The issue is the CC-BY only:
```
           -   license_expression: unknown-license-reference
                license_expression_spdx: LicenseRef-scancode-unknown-license-reference
                matches:
                    -   license_expression: unknown-license-reference
                        license_expression_spdx: LicenseRef-scancode-unknown-license-reference
                        from_file: foo
                        start_line: 11
                        end_line: 12
                        matcher: 2-aho
                        score: '50.0'
                        matched_length: 2
                        match_coverage: '100.0'
                        rule_relevance: 50
                        rule_identifier: license-intro_2.RULE
                        rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/license-intro_2.RULE
                        matched_text: |
                            The ping sound effect (ping.mp3) in TourDeFlex3/src/effects/assets is licensed
                            under Creative Commons 3.0. The original file can be found here:
                        matched_text_diagnostics: |
                            licensed
                            under
```
