### ISSUE TITLE
A url link to artistic-perl-1.0 is detected as `free-unknown`

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#4385]
A url link to artistic-perl-1.0 is detected as `free-unknown`.
```
    - score: '100.0'
      matcher: 2-aho
      end_line: 221
      rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/free-unknown_96.RULE
      from_file:
      start_line: 221
      matched_text: (L<http://opensource.org/licenses/Artistic-Perl-1.0>).
      match_coverage: '100.0'
      matched_length: 4
      rule_relevance: 100
      rule_identifier: free-unknown_96.RULE
      license_expression: free-unknown
      license_expression_spdx: LicenseRef-scancode-free-unknown
```

The link should have enough clue to detect `artistic-perl-1.0` instead.
