### ISSUE TITLE
Obvious `gpl-2.0` text is detected as `unknown-license-reference`

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#4387]
```
    - score: '100.0'
      matcher: 2-aho
      end_line: 59
      rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/bsd-new_or_gpl-2.0_54.RULE
      from_file:
      start_line: 58
      matched_text: |
        // The psx package is licensed with a (you choose) BSD 3-clause or
        // GPL2. See LICENSE file for details.
      match_coverage: '100.0'
      matched_length: 9
      rule_relevance: 100
      rule_identifier: bsd-new_or_gpl-2.0_54.RULE
      license_expression: bsd-new OR gpl-2.0
      license_expression_spdx: BSD-3-Clause OR GPL-2.0-only
    - score: '100.0'
      matcher: 2-aho
      end_line: 59
      rule_url: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/unknown_10.RULE
      from_file:
      start_line: 59
      matched_text: // GPL2. See LICENSE file for details.
      match_coverage: '100.0'
      matched_length: 5
      rule_relevance: 100
      rule_identifier: unknown_10.RULE
      license_expression: unknown-license-reference
      license_expression_spdx: LicenseRef-scancode-unknown-license-reference
```

The `matched_text: // GPL2. See LICENSE file for details.` should be returned as `gpl-2.0` instead of `unknown-license-reference`
