### ISSUE TITLE
Correct format for lxml-3.6.4.ABOUT

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#718]
https://github.com/nexB/scancode-toolkit/blob/develop/thirdparty/prod/lxml-3.6.4.ABOUT

From to the doc (https://docs.google.com/document/d/1Le0bahKIUxWfFD2j8uvbyNjTjD8Up4vPyfMLML9OEGo), "Top level known objects are ALWAYS plural".
Should the 'component' becomes 'components', 'package' becomes 'packages', 'license' becomes 'licenses'

Example from the doc:
```
    packages:
      - download_url: http://pypi.python.org/packages/source/b/bitarray/bitarray-0.8.1.tar.gz
        sha1: 468456384529abcdef342
    license_expression: psf
    licenses:
      - source: scancode.com
        key: psf
        text_file: PSF.LICENSE
```

Should we update the ABOUT to the following instead?
```
    packages:
      - checksum: md5:6dd7314233029d9dab0156e7b1c7830b
        download_url: https://pypi.python.org/packages/4f/3f/cf6daac551fc36cddafa1a71ed48ea5fd642e5feabd3a0d83b8c3dfd0cb4/lxml-3.6.4.tar.gz

    copyright: Copyright (c) 2004 Infrae. All rights reserved.
    licenses:
      - text_file: lxml.LICENSE
        expression: bsd-new and (mit and gpl-2.0-plus and zope-2.0 and zlib)
        text_file: lxml.LICENSE
        notice_file: lxml.NOTICE

    vcs:
      - tool: git
        branch: lxml-3.3
        repository: https://github.com/lxml/lxml.git
```
